### PR TITLE
Remove composer.lock

### PR DESCRIPTION
**Pull request by aivus**
I propose to remove `composer.lock` file because it rudimental.
This file makes sense in application, not libraries.

### CODE REVIEW

**Comment by CHH** [comment]
I will close this PR.

Committing a `composer.lock` is very useful for running the tests on the CI system with the same dependencies (PHPUnit and more) that a contributor had when they tested the code locally.

**Comment by CHH** [comment]
See also https://getcomposer.org/doc/02-libraries.md#lock-file

**Comment by aivus** [comment]
There is a lot of opinions about lock-file.

When this package required in any application, lock file is not used. So, tests could use dependencies from lock file, when end application will use another dep versions.

BTW, current tests don't use lock file:
https://github.com/hochstrasserio/wirecard-bundle/blob/f3ef618ea8e409985d7ee2b0b78e95ead51c6b66/.travis.yml#L22

**Comment by CHH** [comment]
@aivus thanks for the heads-up regarding the CI. Will have a look.

**Pull request closed without merging**
